### ISSUE TITLE
Getting 400 Bad Request

### ISSUE THREAD

**Issue by beeing** [yi/node-clickhouse-cargo#1]
Hi, thanks for this library.

I'm trying this out but I'm not able to get it to send the log file to clickhouse server.

It will return status 400 but without any helpful error message.

Also, I noticed that when there is error, it will cause an unhandled error which will crash the nodejs app. Should it just continue running but waiting for log files to be uploaded later?

Thanks in advance!

**Comment by beeing** [comment]
This is a simple code that I'm testing out.

```js
const cargo = require('clickhouse-cargo')

cargo.init({...})
const log = cargo.createCargo('db.log')
log.push(new Date(), 'some message')
```

**Comment by yi** [comment]
Looks like a request payload format error. 

1. what is the db schema of db.log?
2. try `log.push(Date.now() / 1000 >>> 0, 'some message')`

Detailed explanation:
Getting a 400 response from the server means 1. that request had reached the clickhouse server and 2. that request was rejected by the clickhouse server. 

Cargo uses [response-buffering](https://clickhouse.com/docs/en/interfaces/http/#response-buffering) for batch insertion, thus you may not see the details of the error from the http response. 

So just tail /var/log/clickhouse-server/clickhouse-server.error.log on that clickhouse server, and the log will tell you the detail error of the 400 bad request.

**Comment by beeing** [comment]
Thanks I managed to fix it after looking at the error logs.

However the DateTime is still an issue. When query from /play, the date appears as 1970 instead of today's date.

I tried using  `+new Date()` and it will cause Bad Request.

**Comment by yi** [comment]
> When query from /play, the date appears as 1970 instead of today's date

Check the commit files in ./cargo_files folder to see what actually is going to be committed into clickhouse server.

---

This cargo module is designed for inserting large number of records in a few batches. Thus it will be helpful to have some sort of insertion generator/validation.

I'd used Joi.js for a while, and found it consumed too much cpu power, and following is an example of how we are currently using the cargo module:


```coffeescript


## Factory function
gen_PushToClickhouseCargo  = (clickhouseSchema, tableName)->
  theCargo = createCargo(tableName)

  for item, idx in clickhouseSchema
    item.pos = idx

  #debuglog "[gen_PushToClickhouseCargo] clickhouseSchema:", clickhouseSchema

  proc = (payload)->
    assert payload, "missing payload"
    arr = []   

    #debuglog "[_pushToClickhouseCargo] payload:", payload
    for item in clickhouseSchema
      {key, required, autofill, pos, validator, normalisor, nullable } = item
      #debuglog "[_pushToClickhouseCargo] item:", item
      givenData = payload[key]
      if nullable and ((givenData is undefined) or (givenData is null))
        # nullable value
        arr[pos] = null
      else
        givenData = autofill() if (typeof(autofill) is "function") and ((givenData is undefined) or (givenData is null))
        assert(givenData?, "mssing required `#{key}` on payload") if required
        givenData = normalisor(givenData) if normalisor?
        assert(validator(givenData), "invalid data:#{givenData} for `#{key}`") if validator?
        arr[pos] = givenData

    #debuglog "[_pushToClickhouseCargo:#{tableName}] to push arr:", arr
    theCargo.push(arr...)
    return

  return proc

_normaliseToString = (val)->  return String(val || '').trim()


## Clickhouse table schema
CH_SCHEMA_DIGEST = [
    key : 'date'
    required : true
    autofill : -> Date.now() / 1000 >>> 0
  ,
    key : 'cat'
    normalisor : _normaliseToString
  ,
    key : 'prop'
    normalisor : _normaliseToString
  ,
    key : 'val'
    normalisor : _normaliseToString
  ,
    key : 'comment'
    normalisor : _normaliseToString
]

## generate an insert function
pushToClickhouseCargo = gen_PushToClickhouseCargo(CH_SCHEMA_DIGEST, "table_name")

# Usage exmpales
pushToClickhouseCargo({cat:CAT_USER, prop:PROP_COUNT_TOTAL, val: countTotal})
pushToClickhouseCargo({cat:CAT_USER, prop:PROP_COUNT_EXPIRED, val: countPlanExpired})
pushToClickhouseCargo({cat:CAT_USER, prop:PROP_COUNT_OVER_USAGE, val: countOverUsage})
```

**Comment by beeing** [comment]
Just wondering if I using DateTime64, why I'm not able to send the `Date.now()` to ClickHouse without dividing by 1000?

Thanks!

**Comment by beeing** [comment]
Anyway, found out that the DateTime64 can only be used with precision 3 and when saving to CSV will need to be in string rather than number.

Thanks @yi for the help and great library!
