### ISSUE TITLE
Migrate to js/ts

### ISSUE THREAD

**Issue by restyler** [yi/node-clickhouse-cargo#3]
Hi! I have implemented a very similar mechanism in my API analytics project, but obviously my solution lacks the robustness and features which I might get in a project like node-clickhouse-cargo. 
The only thing preventing me from using your project is esoteric syntax of coffeescript. I understand it is here for historical reasons and it might be too much energy to convert the project to a more conventional js/ts code but I had to create this issue to let you know there are people around who might think pretty much like me. There are wonderful projects like https://github.com/decaffeinate/decaffeinate which might greatly reduce the amount of time required for the migration.

Having third language in a node_modules folder might be too much for many teams, unless it is absolutely critical and I think coffeescript is a good example of a language which was useful 3-5 years ago but is obviously starting to look outdated nowadays. Good luck!

**Comment by no-on3** [comment]
Hi
have you started this ?

**Comment by yi** [comment]
hi, there are js files in /lib/ folder.

Coffeescript is good, it makes things way much simpler.

**Comment by no-on3** [comment]
> hi, there are js files in /lib/ folder.
> 
> Coffeescript is good, it makes things way much simpler.

Hello,
do you allow me to rewrite it in typescript ?
